core/account/urls.py
from django.urls import path , include
from account.views import (LoginView , LoginVerificationView, ProfileWishListView
                           , WelcomePageView, LogoutView, ProfileView, ProfileAddInfoView,ProfileSideBarView
                           ,ProfileCart,Factor)


app_name="account"


urlpatterns = [
    # account
    path('login/', LoginView.as_view(),name='login-page'),
    path('login-verification/', LoginVerificationView.as_view(),name='login-verification-page'),
    path('welcome/', WelcomePageView.as_view(),name='welcome-page'),
    path('logout/', LogoutView.as_view(),name='logout-page'),

    # profile
    path('profile-sidebar/', ProfileSideBarView.as_view(),name='profile-sidebar'),
    path('profile/', ProfileView.as_view(),name='profile-page'),
    path('profile-add-info/', ProfileAddInfoView.as_view(),name='profile-add-info-page'),
    path('profile-wish-list/', ProfileWishListView.as_view(),name='profile-wish-list-page'),
    # path('profile-order-list/', ProfileOrderListView.as_view(),name='profile-order-list-page'),
    path('profile-order/',ProfileCart.as_view(),name='profile-order-list-page'),
    path('profile-order-factor/<str:pk>',Factor.as_view(),name='factor-page'),



]

core/cart/urls.py
from django.urls import path
from cart import views

app_name='cart'

urlpatterns = [
    path('add-to-cart/',views.AddToCart.as_view(),name='add-to-cart'),
    path('cart-list/',views.CartListView.as_view(),name='cart-list'),
    path('delete-cart-item/<int:order_item_id>/',views.DeleteCartItemView.as_view(),name='delete-cart-item'),
    path('change-cart-quantity/',views.ChangeOrderItemQuantityView.as_view(),name='change-cart-quantity'),
    path('shipping/',views.ShippingView.as_view(),name='shipping-page'),

    path('request/', views.PaymentView.as_view(), name='request'),
    path('verify/', views.AfterPaymentView.as_view() , name='verify'),
    path('success-payment/<int:order_id>/', views.SucessPaymentView.as_view() , name='success-payment-page'),
    path('failure-payment/<int:order_id>/', views.FailurePaymentView.as_view() , name='failure-payment-page'),


]

core/home/urls.py
from django.urls import path
from home.views import HomeView , HeaderView , FooterView
from django.views.decorators.cache import cache_page
app_name='home'

urlpatterns = [
    path('', cache_page(15 * 1)(HomeView.as_view()),name='index-page'),
    path('header/', HeaderView.as_view(),name='header-layout'),
    path('footer/', FooterView.as_view(),name='footer-layout'),

]

core/product/urls.py
from django.urls import path
from . import views

app_name='product'

urlpatterns = [
    path('listview/',views.ProductListView.as_view(),name='listview'),
    path('<str:category>/<int:id>/',views.ProductDetailView.as_view(),name='detail'),
    path('wishlist/',views.WishListView.as_view(),name='wish_list'),
    path('search/',views.Search.as_view(),name='search'),
    path('log/',views.login_view,),
]

core/home/models.py
from django.db import models



class SiteSettings(models.Model):
    top_banner = models.ImageField()
    site_logo = models.ImageField()
    left_sidebar_banner_1 = models.ImageField()
    left_sidebar_banner_2 = models.ImageField()
    footer_seo_text = models.TextField()
    is_active = models.BooleanField(default=True)


class Slider(models.Model):
    image = models.ImageField()



class NewsLatter(models.Model):
    email = models.EmailField(unique=True)


    def __str__(self):
        return self.email


class Navbar(models.Model):
    name = models.CharField(max_length=250)
    link = models.CharField(max_length=250, null=True)


    def __str__(self):
        return self.name


class Footer(models.Model):
    name = models.CharField(max_length=250)


    def __str__(self):
        return self.name


class SubFooter(models.Model):
    parent = models.ForeignKey(Footer,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=250)
    link = models.CharField(max_length=250,default="#")


    def __str__(self):
        return self.name

core/templates/layout/footer.html
<footer class="footer mt-3">{% load static %}
    <div class="row">
        <div class="footer-jumpup">
            <div class="container">
                <a href="javascript:void(0)">
                    <span href="javascript:void(0)" class="footer-jumpup-container"><i class="fa fa-angle-up"></i></span>
                </a>
            </div>
        </div>
    </div>
    <div class="col-12">
        <nav class="footer-feature-innerbox mb-1">
            <div class="footer-badge-item">
                <a href="#" class="footer-badge-link">
                    <img src="{% static 'assets/images/footer/delivery.svg' %}">
                    <span class="footer-badge-title">تحویل اکسپرس</span>
                </a>
            </div>
            <div class="footer-badge-item">
                <a href="#" class="footer-badge-link">
                    <img src="{% static 'assets/images/footer/contact-us.svg' %}">
                    <span class="footer-badge-title">پشتیبانی 24 ساعته</span>
                </a>
            </div>
            <div class="footer-badge-item">
                <a href="#" class="footer-badge-link">
                    <img src="{% static 'assets/images/footer/payment-terms.svg' %}">
                    <span class="footer-badge-title">پرداخت درمحل</span>
                </a>
            </div>
            <div class="footer-badge-item">
                <a href="#" class="footer-badge-link">
                    <img src="{% static 'assets/images/footer/return-policy.svg' %}">
                    <span class="footer-badge-title">۷ روز ضمانت بازگشت</span>
                </a>
            </div>
            <div class="footer-badge-item">
                <a href="#" class="footer-badge-link">
                    <img src="{% static 'assets/images/footer/origin-guarantee.svg' %}">
                    <span class="footer-badge-title">ضمانت اصل بودن کالا</span>
                </a>
            </div>
        </nav>
    </div>
    <article class="container-main">
        <div class="footer-middlebar">
            <div class="col-lg-8 col-md-8 col-xs-12 pull-right">
                <div class="footer-links">
                    {% for footer in footers %}
                    
                    <div class="col-lg-4 col-md-4 col-xs-12 pull-right">
                        <nav class="footer-links-col">
                            <div class="headline-links mb-3">
                                <a href="#">
                                    {{footer.name}}
                                </a>
                            </div>
                            <ul class="footer-links-ul">
                                {% for sub_footer in footer.subfooter_set.all %}
                                <li>
                                    <a href="{{sub_footer.link}}">
                                        {{sub_footer.name}}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </nav>
                    </div>
                    {% endfor %}

                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-xs-12 pull-left">
                <div class="footer-form">
                    <form action="{% url "home:footer-layout" %}" method='post' class="form-newsletter mb-4 mt-4">
                        {% csrf_token %}
                        <fieldset>
                            <span class="form-newsletter-title">از تخفیف‌ها و جدیدترین‌های دیجی‌اسمارت
                                باخبرشوید:</span>
                            <div class="form-newsletter-row">
                                <input name="email" type="email" class="input-field-send-email"
                                    placeholder="آدرس ایمیل خود را وارد کنید" required>
                                <button type="submit" class="btn-secondary-send">ارسال</button>
                            </div>
                        </fieldset>
                    </form>
                    <div class="footer-community">
                        <div class="footer-social mb-4 mt-4">
                            <span>دیجی‌اسمارت را در شبکه‌های اجتماعی دنبال کنید:</span>
                            <div class="footer-social">
                                <ul class="footer-ul-social">
                                    <li class="footer-social-item">
                                        <a href="#" class="footer-social-link">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                    <li class="footer-social-item">
                                        <a href="#" class="footer-social-link">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li class="footer-social-item">
                                        <a href="#" class="footer-social-link">
                                            <i class="fa fa-linkedin-square"></i>
                                        </a>
                                    </li>
                                    <li class="footer-social-item">
                                        <a href="#" class="footer-social-link">
                                            <i class="fa fa-telegram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-more-info">
            <div class="footer-description-content">
                <div class="col-xs-8 col-md-8 col-xs-12 pull-right">
                    <div class="footer-content">
                        <article class="footer-seo mt-3">
                            <h1>فروشگاه اینترنتی دیجی‌اسمارت، بررسی، انتخاب و خرید آنلاین</h1>
                            <p>دیجی‌اسمارت به عنوان یکی از قدیمی‌ترین فروشگاه های اینترنتی با بیش از یک دهه تجربه،
                                با پایبندی به سه اصل، پرداخت در محل، 7 روز ضمانت بازگشت کالا و تضمین اصل‌بودن کالا
                                موفق شده تا همگام با فروشگاه‌های معتبر جهان، به بزرگ‌ترین فروشگاه اینترنتی ایران
                                تبدیل شود. به محض ورود به سایت دیجی‌اسمارت با دنیایی از کالا رو به رو می‌شوید! هر
                                آنچه که نیاز دارید و به ذهن شما خطور می‌کند در اینجا پیدا خواهید کرد.</p>
                        </article>
                    </div>
                </div>
                <div class="">
                    <div class="col-lg-4 col-md-4 col-xs-12 pull-left">
                        <aside>
                            <ul class="footer-safety-partner mt-4 pull-left">
                                <li class="footer-safety-partner-1">
                                    <a href="#">
                                        <img src="{% static 'assets/images/footer/license/L-2.png' %}">
                                    </a>
                                </li>
                                <li class="footer-safety-partner-1">
                                    <a href="#">
                                        <img src="{% static 'assets/images/footer/license/L-1.png' %}">
                                    </a>
                                </li>
                            </ul>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="footer-copyright-text">
                استفاده از مطالب فروشگاه اینترنتی دیجی‌اسمارت فقط برای مقاصد غیرتجاری و با ذکر منبع
                بلامانع است. کلیه حقوق این سایت متعلق به شرکت نوآوران فن آوازه (فروشگاه آنلاین دیجی‌اسمارت) می‌باشد.
            </div>
        </div>
    </article>
</footer>

core/templates/layout/header.html
<header>{% load static %}
    <aside class="adplacement-top-header">
        <a href="#" class="adplacement-item"style="
        background-image: url({{site_setting.top_banner.url}});" title="شگفت سوپرمارکتی"></a>
    </aside>
    <div class="container-main">
        <div class="col-lg-8 col-md-8 col-xs-12 pull-right">
            <div class="header-right">
                <div class="logo">
                    <a href="/"><img src="{{site_setting.site_logo.url}}"></a>
                </div>
                <div class="col-lg-9 col-md-9 col-xs-12 pull-right">
                    <div class="search-header">
                        <form method='GET' action="{% url 'product:search' %}">
                            <input name='para' type="text" class="search-input"
                                placeholder="نام کالا، برند و یا دسته مورد نظر خود را جستجو کنید…">
                            <button type="submit" class="button-search">
                                <img src="{% static 'assets/images/search.png' %}">
                            </button>
                        </form>
                        <div class="search-result">
                            <ul class="search-result-list mb-0">
                                {% for navbar in navbars %}
                                <li>
                                    <a href="{{navbar.link}}"><i class="mdi mdi-clock-outline"></i>
                                        {{navbar.name}}
                                        <button class="btn btn-light btn-remove-search" type="submit">
                                            <i class="mdi mdi-close"></i>
                                        </button>
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-xs-12 pull-left">
            <div class="header-left">
                <ul class="nav-lr">
                    <li class="nav-item-account">
                        {% if request.user.is_authenticated %}
                        <a href="#">
                            {% if profile.avatar %}
                            <img src="{{profile.avatar.url}}" height="32px" width="32px">
                            {% else %}
                            <img src="{% static 'assets/images/user.png' %}" alt="user">
                            {% endif %}
                            حساب کاربری                                
                            <div class="dropdown-menu">
                                <ul>
                                    <li class="dropdown-menu-item">
                                        <a href="{% url "account:profile-page" %}" class="dropdown-item">
                                            <i class="mdi mdi-account-card-details-outline"></i>
                                            حساب کاربری من
                                        </a>
                                    </li>
                                    <li class="dropdown-menu-item">
                                        <a href="{% url "account:logout-page" %}" class="dropdown-item">
                                            <i class="mdi mdi-logout-variant"></i>
                                            خروج از حساب
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </a>
                        {% else %}
                        <a href="{% url "account:login-page" %}">
                            <img src="{% static 'assets/images/user.png' %}" alt="user">
                           ورود به حساب کاربری 
                        </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
        <div class="overlay-search-box"></div>
    </div>
    <nav class="main-menu">
        <div class="container-main">
            <div>
                <ul class="list-menu">
                    {% for navbar in navbars %}
                    <li class="item-list-menu megamenu">
                        <a href="{{navbar.link}}" class="list-category"> {{navbar.name}}</a>
                    </li>
                    {% endfor %}
                    <li class="nav-item-account nav-item-cart">
                        <div class="header-cart-interest">
                            <a href="{% url 'product:wish_list' %}" class="d-block">
                                <i class="fa fa-heart"></i>
                                <span class="counter">{{wishlist.product.count}}</span>
                            </a>
                        </div>
                        <div class="header-cart-basket">
                            <a href="{% url 'cart:cart-list' %}">
                                <span class="mdi mdi-shopping"></span>
                                سبد خرید
                                <span class="count">{{cart_items.count}}</span>
                            </a>
                            <div class="dropdown-menu-cart">
                                <div class="dropdown-header">
                                    <a href="{% url 'cart:cart-list' %}" class="view-cart">مشاهده سبد خرید</a>
                                </div>
                                <div class="wrapper">
                                    <div class="scrollbar" id="style-1">
                                        <div class="force-overflow">
                                            <ul class="dropdown-list">
                                                {% for cart in cart_items %}
                                                <a href="{% url "product:detail" category=cart.product_variant.product.category.name id=cart.product_variant.product.id %}">
                                                    <li class="dropdown-item">
                                                        <div class="title-cart">
                                                            <img src="{{cart.product_variant.product.image.url}}">
                                                            <h3>{{cart.product_variant.product.name}}</h3>
                                                            <div class="price">{{cart.product_variant.product.price}}
                                                                <span>تومان</span>
                                                            </div>
                                                            <button class="btn-delete">
                                                                <span class="mdi mdi-close"></span>
                                                            </button>
                                                        </div>
                                                    </li>
                                                </a>
                                                {% endfor %}
                                                

                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="footer-dropdown">
                                    <a href="{% url "cart:cart-list" %}" class="checkout">تسویه حساب</a>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="nav-btn nav-slider">
            <span class="linee1"></span>
            <span class="linee2"></span>
            <span class="linee3"></span>
        </div>
    </nav>
    <nav class="sidebar">
        <div class="nav-header">
            <div class="header-cover"></div>
            <div class="logo-wrap">
                <a class="logo-icon" href="#"><img alt="logo-icon" src="{% static 'assets/images/logo.png' %}" width="40"></a>
            </div>
        </div>
        <ul class="nav-categories ul-base">
            {% for navbar in navbars %}
            <li><a href="{{navbar.link}}">{{navbar.name}}</a></li>
            {% endfor %}
        </ul>
    </nav>
    <div class="overlay"></div>

</header>

core/templates/layout/product_small_item.html
<div class="owl-item active" style="width: 309.083px; margin-left: 10px;">
    <div class="item">
        <a href="{% url "product:detail" category=product.category.name id=product.id %}" class="d-inline-block">
            <img src="{{product.image.url}}" class="img-fluid" alt="">
        </a>
        <h2 class="post-title">
            <a href="{% url "product:detail" category=product.category.name id=product.id %}">
                {{product.name}}
            </a>
        </h2>
        <div class="price">
            <ins>
                <span> {% for tvsize in product.tvsize_set.all %}{% if forloop.first %}{{tvsize.calculate_price}}{% endif %}{% endfor %} 
                    <span>تومان</span>
                </span>
            </ins>
        </div>
        {% comment %} <div class="actions">
            <ul>
                <li class="action-item like">
                    <button class="btn btn-light add-favorites add-product-wishes"
                        type="submit" title="علاقه مندی">
                        <i class="mdi mdi-heart"></i>
                    </button>
                </li>
                <li class="action-item compare">
                    <button class="btn btn-light btn-compare" type="submit"
                        title="مقایسه">
                        <i class="mdi mdi-compare"></i>
                    </button>
                </li>
                <li class="action-item add-to-cart">
                    <button class="btn btn-light btn-add-to-cart" type="submit"
                        title="سبد خرید">
                        <i class="mdi mdi-shopping"></i>
                    </button>
                </li>
            </ul>
        </div> {% endcomment %}
    </div>
</div>

core/templates/layout/profile-sidebar.html
{% load static %}
<div class="col-lg-3 col-md-3 col-xs-12 pull-right">
    <section class="page-aside">
        <div class="sidebar-wrapper">
            <div class="box-sidebar">
                <div class="profile-box">
                    <div class="profile-box-avator">
                        <a href="#">
                            {% if profile.avatar %}
                            <img src="{{profile.avatar.url}}">
                            {% else %}
                            <img src="{% static 'assets/images/profile/user-profile.svg' %}">
                            {% endif %}
                        </a>
                    </div>
                    <div class="profile-box-content">
                        <span class="profile-box-nameuser">{{profile.full_name}}</span>
                        <span class="profile-box-phone">شماره همراه : {{user.phone_number}}</span>
                        <a href="#"><span class="profile-box-row-arrow">دیجی کلاب : {{profile.shop_point}} امتیاز</span></a>
                    </div>
                    <div class="profile-box-tabs">
                        <a href="#" class="profile-box-tab">تغییر رمز</a>
                        <a href="{% url "account:logout-page" %}" class="profile-box-tab-sign-out">خروج از حساب</a>
                    </div>
                </div>
            </div>
            <div class="box-sidebar">
                <span class="box-header-sidebar">حساب کاربری شما</span>
                <ul class="profile-menu-items">
                    <li>
                        <a href="{% url "account:profile-page" %}" id='profile' class="profile-menu-url">
                            <span class="mdi mdi-account-outline"></span>
                            پروفایل</a>
                    </li>
                    <li>
                        <a href="{% url "account:profile-order-list-page" %}" id='orders'  class="profile-menu-url">
                            <span class="fa fa-shopping-basket"></span>
                            همه سفارش ها</a>
                    </li>
                    <li>
                        <a href="#" class="profile-menu-url">
                            <span class="fa fa-file-text-o"></span>
                            در خواست مرجوعی</a>
                    </li>
                    <li>
                        <a href="{% url "account:profile-wish-list-page" %}" id="wish-list" class="profile-menu-url">
                            <span class="fa fa-star-o"></span>
                            لیست علاقه مندی ها</a>
                    </li>
                    <li>
                        <a href="#" class="profile-menu-url">
                            <span class="fa fa-file-text-o"></span>
                            نقد و نظرات</a>
                    </li>
                    <li>
                        <a href="#" class="profile-menu-url">
                            <span class="mdi mdi-map"></span>
                            آدرس ها</a>
                    </li>
                    <li>
                        <a href="#" class="profile-menu-url">
                            <span class="fa fa-clock-o"></span>
                            بازدید های اخیر</a>
                    </li>
                </ul>
            </div>
        </div>
    </section>
</div>