core/account/urls.py
from django.urls import path , include
from account.views import (LoginView , LoginVerificationView, ProfileWishListView
                           , WelcomePageView, LogoutView, ProfileView, ProfileAddInfoView,ProfileSideBarView
                           ,ProfileCart,Factor)


app_name="account"


urlpatterns = [
    # account
    path('login/', LoginView.as_view(),name='login-page'),
    path('login-verification/', LoginVerificationView.as_view(),name='login-verification-page'),
    path('welcome/', WelcomePageView.as_view(),name='welcome-page'),
    path('logout/', LogoutView.as_view(),name='logout-page'),

    # profile
    path('profile-sidebar/', ProfileSideBarView.as_view(),name='profile-sidebar'),
    path('profile/', ProfileView.as_view(),name='profile-page'),
    path('profile-add-info/', ProfileAddInfoView.as_view(),name='profile-add-info-page'),
    path('profile-wish-list/', ProfileWishListView.as_view(),name='profile-wish-list-page'),
    # path('profile-order-list/', ProfileOrderListView.as_view(),name='profile-order-list-page'),
    path('profile-order/',ProfileCart.as_view(),name='profile-order-list-page'),
    path('profile-order-factor/<str:pk>',Factor.as_view(),name='factor-page'),



]

core/cart/urls.py
from django.urls import path
from cart import views

app_name='cart'

urlpatterns = [
    path('add-to-cart/',views.AddToCart.as_view(),name='add-to-cart'),
    path('cart-list/',views.CartListView.as_view(),name='cart-list'),
    path('delete-cart-item/<int:order_item_id>/',views.DeleteCartItemView.as_view(),name='delete-cart-item'),
    path('change-cart-quantity/',views.ChangeOrderItemQuantityView.as_view(),name='change-cart-quantity'),
    path('shipping/',views.ShippingView.as_view(),name='shipping-page'),

    path('request/', views.PaymentView.as_view(), name='request'),
    path('verify/', views.AfterPaymentView.as_view() , name='verify'),
    path('success-payment/<int:order_id>/', views.SucessPaymentView.as_view() , name='success-payment-page'),
    path('failure-payment/<int:order_id>/', views.FailurePaymentView.as_view() , name='failure-payment-page'),


]

core/home/urls.py
from django.urls import path
from home.views import HomeView , HeaderView , FooterView
from django.views.decorators.cache import cache_page
app_name='home'

urlpatterns = [
    path('', cache_page(15 * 1)(HomeView.as_view()),name='index-page'),
    path('header/', HeaderView.as_view(),name='header-layout'),
    path('footer/', FooterView.as_view(),name='footer-layout'),

]

core/product/urls.py
from django.urls import path
from . import views

app_name='product'

urlpatterns = [
    path('listview/',views.ProductListView.as_view(),name='listview'),
    path('<str:category>/<int:id>/',views.ProductDetailView.as_view(),name='detail'),
    path('wishlist/',views.WishListView.as_view(),name='wish_list'),
    path('search/',views.Search.as_view(),name='search'),
    path('log/',views.login_view,),
]

core/cart/models.py
import random , string

from django.db import models
from django.db.models import Sum , F

import jdatetime

class Order(models.Model):
    shopping_id = models.SlugField(unique=True, blank=True,null=True,db_index=True)
    profile = models.ForeignKey('account.Profile',on_delete=models.CASCADE)
    full_name = models.CharField(max_length=250,null=True,blank=True)
    address = models.TextField(null=True,blank=True)
    phone_number = models.CharField(max_length=15,null=True,blank=True)
    paid_amount = models.IntegerField(blank=True,null=True)

    in_proccesing = models.BooleanField(default=False)
    is_confirmed = models.BooleanField(default=False)
    prepare_product = models.BooleanField(default=False)
    sended = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False)
    cancelled = models.BooleanField(default=False)

    score = models.IntegerField(default=0)

    payment_date = models.DateTimeField(null=True,blank=True)

    def __str__(self):
        return str(self.profile) + " ////////// " + str(self.id)

    def calculate_paid_amount_needed(self) -> int:
        order_detail = OrderItem.objects.filter(order=self)
        total_price = order_detail.aggregate(
            total_spent=Sum(
            F('quantity') * (F('product_variant__price_difference') + F('product_variant__product__price')),
            output_field=models.IntegerField()
            )
        )
        return total_price['total_spent']

    @staticmethod
    def start_ship_date() -> str:
        jdatetime.set_locale(jdatetime.FA_LOCALE)
        today = jdatetime.date.today()
        start_delta_time = jdatetime.timedelta(days=4)
        start_date = today + start_delta_time
        formatted_start_date = f"{start_date.year}-{start_date.jmonth()}-{start_date.day}"
        return formatted_start_date

    @staticmethod
    def end_ship_date() -> str:
        jdatetime.set_locale(jdatetime.FA_LOCALE)
        today = jdatetime.date.today()
        finish_delta_time = jdatetime.timedelta(days=8)
        finish_date = today + finish_delta_time
        formatted_finish_date = f"{finish_date.year}-{finish_date.jmonth()}-{finish_date.day}"
        return formatted_finish_date

    @staticmethod
    def calculate_score(paid_amount) -> None:
        return paid_amount / 1000


    def save(self, *args, **kwargs):
        while not self.shopping_id:
            new_shopping_id = ''.join(
                random.sample(string.ascii_letters, 2) +
                random.sample(string.digits, 2) +
                random.sample(string.ascii_letters, 2),
            )

            if not Order.objects.filter(shopping_id=new_shopping_id).exists():
                self.shopping_id = new_shopping_id

        super().save(*args, **kwargs)

    def get_all_quantity(self):
        order_detail = OrderItem.objects.filter(order=self)
        order_item_quantity = order_detail.aggregate(
            total_quantity=Sum(
            F('quantity')
            )
        )
        return order_item_quantity['total_quantity']


class OrderItem(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    product_variant = models.ForeignKey('product.TvSize',on_delete=models.CASCADE)
    final_price = models.IntegerField(blank=True,null=True)
    selected_size = models.CharField(max_length=25,null=True,blank=True)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return str(self.order_id) + " ////////// " + self.product_variant.product.name

core/cart/forms.py
from typing import Any

from django import forms
from django.core.exceptions import ValidationError

from cart.models import OrderItem
from product.models import TvSize


class AddToCartForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['product_variant','quantity']

    def clean(self) -> dict[str, Any]:
        product_variation = self.cleaned_data.get('product_variant',None)
        if product_variation is None:
            raise ValidationError("some error caused.pleas try again later")

        product = product_variation.product
        if product.is_show == False:
            raise ValidationError("some error caused.pleas try again later")

        quantity = self.cleaned_data.get('quantity')
        if quantity < 1 :
            raise ValidationError("some error caused.pleas try again later")

        if quantity > product_variation.count :
            raise ValidationError("تعداد انتخابی شما بیشتر از موجودی انبار می باشد")

        return self.cleaned_data

core/cart/views.py
import requests
import json

from django.shortcuts import render , redirect ,get_object_or_404
from django.views.generic import View
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum , F
from django.db import transaction
from django.http import JsonResponse,Http404
from django.urls import reverse_lazy , reverse
from django.conf import settings
from django.utils import timezone

from cart.forms import AddToCartForm
from cart.models import Order , OrderItem
from account.models import Profile
from product.models import TvSize
# Create your views here.


import logging
logger = logging.getLogger(__name__)


class AddToCart(LoginRequiredMixin,View):
    login_url = reverse_lazy("account:login-page")
    def get(self,request):

        form = AddToCartForm(request.GET)
        if form.is_valid():
            profile = Profile.objects.get(user=request.user)
            product_variation = form.cleaned_data.get('product_variant')
            quantity = form.cleaned_data.get('quantity')

            order , _ = Order.objects.get_or_create(profile=profile,in_proccesing=False)

            order_item = OrderItem.objects.filter(order_id=order.id,product_variant=product_variation)
            if order_item.exists():
                msg = 'این محصول در سبد خرید شما وجود دارد'
                messages.info(request,msg)
            else:
                OrderItem.objects.create(order=order,product_variant=product_variation,
                                        quantity=quantity)
                msg = 'این محصول با موفقیت به سبد محصول شما اضافه شد'
                messages.success(request,msg)
        else:
            # error_msg = 'مشکلی پیش امده است لطفا دوباره تلاش کنید.'
            messages.error(request,form.errors.get('__all__'))

        path = request.GET.get('next','/')
        return redirect(path)



class CartListView(LoginRequiredMixin,View):
    login_url = reverse_lazy("account:login-page")

    def get(self,request):
        profile = Profile.objects.get(user=request.user)
        order , created = Order.objects.prefetch_related('orderitem_set').get_or_create(profile=profile,in_proccesing=False)

        if created or not order.orderitem_set.exists():
            return render(request,'cart-empty.html')

        context = {
            'order' : order,  # TODO: we need better quary to avoid n+1 problem (select related?)
        }
        return render(request,'cart.html',context)


class DeleteCartItemView(LoginRequiredMixin,View):
    login_url = reverse_lazy("account:login-page")

    def get(self,request,order_item_id):
        order_item = OrderItem.objects.filter(id=order_item_id,order__profile__user=request.user)
        if order_item.exists():
            order_item.delete()
            msg = 'محصول با موفقیت از سبد خرید شما حذف شد'
            messages.success(request,msg)
        else:
            msg = 'مشکلی در سیستم رخ داده است. لطفا بعدا دوباره امتحان کنید.'
            messages.error(request,msg)
        return redirect("cart:cart-list")


class ChangeOrderItemQuantityView(LoginRequiredMixin,View):
    login_url = reverse_lazy("account:login-page")

    def get(self,request):
        form = AddToCartForm(request.GET)
        if form.is_valid():
            product_variation = form.cleaned_data.get('product_variant')
            quantity = form.cleaned_data.get('quantity')
            OrderItem.objects.filter(product_variant=product_variation).update(quantity=quantity)
            msg = 'تعداد محصول با موفقیت تغییر کرد'
        else:
            msg = 'مشکلی در سیستم رخ داده است. لطفا بعدا دوباره امتحان کنید.'

        return JsonResponse({'msg':msg})


class ShippingView(LoginRequiredMixin,View):
    login_url = reverse_lazy("account:login-page")
    def get(self,request):
        profile = Profile.objects.get(user=request.user)
        order , _ = Order.objects.prefetch_related('orderitem_set').get_or_create(profile=profile,in_proccesing=False)

        if  not order.orderitem_set.exists():
            return render(request,'cart-empty.html')

        paid_amount_needed = order.calculate_paid_amount_needed()

        context = {
            'order' : order,
            'paid_amount_needed' : paid_amount_needed,
        }
        return render(request,'shipping-payment.html',context)


class PaymentView(LoginRequiredMixin,View):
    login_url = reverse_lazy("account:login-page")
    def get(self,request):
        profile = Profile.objects.get(user=request.user)
        order = Order.objects.filter(profile=profile,in_proccesing=False).last()

        if not order.orderitem_set.exists():
            return render(request,'cart-empty.html')

        CallbackURL = request.build_absolute_uri(reverse('cart:verify'))

        data = {
            "MerchantID": settings.MERCHANTID,
            "Amount": order.calculate_paid_amount_needed(),
            "Description": "این تراکنش صرفا جهت تست می باشد",
            "Phone": 'YOUR_PHONE_NUMBER',
            "CallbackURL": CallbackURL,
        }

        data = json.dumps(data)

        headers = {'content-type': 'application/json', 'content-length': str(len(data)) }

        try:
            response = requests.post(settings.ZP_API_REQUEST, data=data,headers=headers, timeout=100)

            if response.status_code == 200:
                response = response.json()
                if response['Status'] == 100:
                    return redirect(settings.ZP_API_STARTPAY + str(response['Authority']))
                else:
                    messages.error(request,str(response['Status']))
                    return redirect('cart:shipping-page')
            return JsonResponse(response.json(),safe=False)

        except requests.exceptions.Timeout:
            messages.error(request,'timeout')
            return redirect('cart:shipping-page')

        except requests.exceptions.ConnectionError:
            messages.error(request,'connection error')
            return redirect('cart:shipping-page')


class AfterPaymentView(LoginRequiredMixin,View):
    login_url = reverse_lazy("account:login-page")

    def get(self,request):
        profile = Profile.objects.get(user=request.user)
        order = Order.objects.prefetch_related('orderitem_set').filter(profile=profile,in_proccesing=False).last()

        if not order.orderitem_set.exists():
            return render(request,'cart-empty.html')

        amount = order.calculate_paid_amount_needed()
        data = {
            "MerchantID": settings.MERCHANTID,
            "Amount": amount,
            "Authority": request.GET.get('Authority'),
        }

        data = json.dumps(data)
        headers = {'content-type': 'application/json', 'content-length': str(len(data)) }
        response = requests.post(settings.ZP_API_VERIFY, data=data,headers=headers)

        if response.status_code == 200:
            response_data = response.json()

            if response_data.get('Status') == 100:
                self.save_order_and_orderitem_data(order,profile,request.user.phone_number, amount)
                request.session['state'] = 'success'
                return redirect('cart:success-payment-page', order_id=order.id)
            else:
                request.session['state'] = 'unsuccess'
                return redirect('cart:failure-payment-page', order_id=order.id)

        return JsonResponse(response.json(), safe=False)

    @transaction.atomic
    def save_order_and_orderitem_data(self,order,profile,phone_number,amount) -> None:
        order.full_name = profile.full_name
        order.address = profile.address
        order.phone_number = phone_number
        order.paid_amount = amount
        order.in_proccesing = True
        order.payment_date = timezone.now()
        order.score = order.calculate_score(amount)
        order.save()

        for order_item in order.orderitem_set.all():
            final_price = order_item.product_variant.price_difference + order_item.product_variant.product.price
            order_item.final_price = final_price
            order_item.selected_size = order_item.product_variant.size
            order_item.save()

            TvSize.objects.filter(id=order_item.product_variant.id).update(count=F('count') - order_item.quantity)


class SucessPaymentView(LoginRequiredMixin,View):
    login_url = reverse_lazy("account:login-page")
    def get(self,request,order_id):
        if request.session.get('state') == 'success':
            del request.session['state']
            order = get_object_or_404(Order,id=order_id)
            context = {
                'order' : order
            }
            return render(request,'shipping-complate-buy.html',context)
        else:
            raise Http404()


class FailurePaymentView(LoginRequiredMixin,View):
    login_url = reverse_lazy("account:login-page")
    def get(self,request,order_id):
        if request.session.get('state') == 'unsuccess':
            del request.session['state']
            order = get_object_or_404(Order,id=order_id)
            context = {
                'order' : order
            }
            return render(request,'shipping-no-complate-buy.html',context)
        else:
            raise Http404()

core/templates/factor.html
{% load humanize %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>فاکتور فروش</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px;
            text-align: right;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
        .total {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h2>فاکتور فروش {{order.shopping_id}}</h2>
    <table>
        <thead>
            <tr>
                <th>مورد</th>
                <th>تعداد</th>
                <th>قیمت</th>
                <th>جمع</th>
            </tr>
        </thead>
        <tbody>
            {% for product in order_item %}
            <tr>
                <td>{{product.product_variant.product.name}} با سایز  {{product.product_variant.size}}</td>
                <td>{{product.quantity}}</td>
                <td>{{product.final_price | intcomma}}</td>
                <td>{% widthratio product.quantity 1 product.final_price as total_value%} {{total_value | intcomma }} </td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="total">جمع کل</td>
                <td class="total">{{order.paid_amount | intcomma}}</td>
            </tr>
        </tfoot>
    </table>
</body>
</html>

core/templates/profile-additional-info.html
{% extends "base.html" %}
{% load static %}
{% load render_partial %}

{% block breadcrumb %}
<!--profile------------------------------------>
<div class="container-main">
    <div class="col-12">
        <div class="breadcrumb-container">
            <ul class="js-breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url "home:index-page" %}" class="breadcrumb-link">خانه</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url "account:profile-page" %}" class="breadcrumb-link">پروفایل</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#" class="breadcrumb-link active-breadcrumb">ویرایش اطلاعات شخصی</a>
                </li>
            </ul>
        </div>
    </div>
    {% render_partial  "account:profile-sidebar" %}
{% endblock breadcrumb %}
    

{% block main %}
    <div class="col-lg-9 col-md-9 col-xs-12 pull-left">
        <section class="page-contents">
            <div class="profile-content">
                <div class="profile-navbar">
                    <div class="profile-navbar-back-alignment">
                        <a href="{% url "account:profile-page" %}" class="profile-navbar-btn-back">بازگشت</a>
                        <h4 class="edit-personal">ویرایش اطلاعات شخصی</h4>
                    </div>
                </div>
                <div class="profile-stats">
                    <form class="profile-stats-row" method='post' enctype="multipart/form-data" action="{% url "account:profile-add-info-page" %}">
                        {% csrf_token %}
                        <fieldset class="form-legal-fieldset">
                            <h4 class="form-legal-headline">حساب شخصی</h4>
                            <div class="form-legal-center">
                                <div class="profile-stats-col">
                                    <div class="profile-stats-content">
                                        <span class="profile-first-title"> نام و نام خوانوادگی:</span>
                                        <input class="ui-input-field" type="text" name="full_name" value="{{profile.full_name}}"
                                            placeholder="نام خود را وارد کنید">
                                    </div>
                                </div>
                            </div>
                            <div class="form-legal-center">
                                <div class="profile-stats-col">
                                    <div class="profile-stats-content">
                                        <span class="profile-first-title"> روز تولد:</span>
                                        <input class="ui-input-field" type="text" name="birth_date" placeholder="مثال : 1-1-1390"
                                               value="{{profile.birth_date.year}}-{{profile.birth_date.month}}-{{profile.birth_date.day}}"
                                            >
                                    </div>
                                </div>
                            </div>
                            <div class="form-legal-center">
                                <div class="profile-stats-col">
                                    <div class="profile-stats-content">
                                        <span class="profile-first-title"> شماره موبایل</span>
                                        <input class="ui-input-field" id="phone-number-input" type="text" value="{{user.phone_number}}"
                                            placeholder="شماره موبایل خود را وارد کنید" disable>
                                    </div>
                                </div>
                            </div>
                            <div class="form-legal-center">
                                <div class="profile-stats-col">
                                    <div class="profile-stats-content">
                                        <span class="profile-first-title">آدرس ایمیل</span>
                                        <input class="ui-input-field" type="email" name="email" value="{{profile.email}}"
                                            placeholder="آدرس ایمیل خود را وارد کنید">
                                    </div>
                                </div>
                            </div>
                            <div class="form-legal-center">
                                <div class="profile-stats-col">
                                    <div class="profile-stats-content">
                                        <span class="profile-first-title">کد پستی</span>
                                        <input class="ui-input-field" type="number" name="postalcode" value="{{profile.postalcode}}"
                                            placeholder="کد پستی خود را وارد کنید">
                                    </div>
                                </div>
                            </div>
                            <div class="form-legal-center">
                                <div class="profile-stats-col">
                                    <div class="profile-stats-content">
                                        <span class="profile-first-title">ادرس محل سکونت</span>
                                        <input class="ui-input-field" type="text" name="address" value="{{profile.address}}"
                                            placeholder="ادرس محل سکونت را وارد کنید">
                                    </div>
                                </div>
                            </div>
                            <div class="form-legal-center">
                                <div class="profile-stats-col">
                                    <div class="profile-stats-content">
                                        <span class="profile-first-title">اواتار</span>
                                        <input class="ui-input-field" type="file" name="avatar"style="height: auto;">
                                        {% if profile.avatar %}
                                        <a href="{{profile.avatar.url}}" target="_blank">عکس فعلی</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="form-legal-center">
                                <div class="profile-stats-col has-diviter">
                                    <div class="profile-stats-content">
                                        <div class="form-auth-row">
                                            <label for="remember" class="ui-checkbox">
                                                <input type="checkbox" value="1" name="recive_newsletter" id="remember" {% if profile.recive_newsletter %}checked{% endif %}>
                                                <span class="ui-checkbox-check"></span>
                                            </label>
                                            <label for="remember" class="remember-me">اشتراک در خبرنامه
                                                دیجی‌ استور</label>
                                        </div>
                                        <div class="form-auth-row">
                                            <label for="remember-2" class="ui-checkbox">
                                                <input type="checkbox" value="1" name="recive_events" id="remember-2" {% if profile.recive_events %}checked{% endif %}>
                                                <span class="ui-checkbox-check"></span>
                                            </label>
                                            <label for="remember-2" class="remember-me">اشتراک در مناسبات
                                                دیجی‌ استور</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <div class="col-12" style="padding:0;">
                            <div class="profile-stats-row form-legal-row-submit">
                                <div class="parent-btn parent-store">
                                    <button class="dk-btn dk-btn-info btn-store" type='submit'>
                                        ثبت اطلاعات کاربری
                                        <i class="fa fa-sign-in"></i>
                                    </button>
                                </div>
                                <a href="{% url "account:profile-page" %}" class="btn btn-default-gray">انصراف</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
</div>
<!--profile------------------------------------>
{% endblock main %}

core/templates/wishlist.html
{% extends "base.html" %}
{% load static %}
{% load render_partial %}

{% block breadcrumb %}
<div class="container-main">
    <div class="col-12">
        <div class="breadcrumb-container">
            <ul class="js-breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url "home:index-page" %}" class="breadcrumb-link">خانه</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#" class="{% url "account:profile-page" %}">حساب کاربری من</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#" class="breadcrumb-link active-breadcrumb">لیست علاقه مندی</a>
                </li>
            </ul>
        </div>
    </div>
    {% render_partial  "account:profile-sidebar" %}
{% endblock breadcrumb %}


{% block main %}
    <div class="col-lg-9 col-md-9 col-xs-12 pull-left">
        <section class="page-contents">
            <div class="profile-content">
                <div class="headline-profile headline-profile-favorites">
                    <ul class="pager-tabs">
                        <li class="pager-tab">لیست علاقه‌مندی‌ها</li>
                        <li class="pager-tab">نمایش
                            <span class="js-favorite-from-count" data-value="1">{{obj_count}}</span>
                            کالا
                        </li>
                    </ul>
                </div>
                <div class="profile-stats">
                    <div class="profile-stats-row">
                        <div class="profile-stats">
                            <section class="profile-wishlist">
                                <ul class="profile-wishlist-listing">
                                    {% if products %}
                                    {% for obj in products %}
                                    <li class="profile-wishlist-list-item">
                                        <div class="profile-wishlist-list-item-thumb">
                                            <a href="{% url 'product:detail' obj.category obj.id %}" class="profile-wishlist-list-item-img">
                                                <img src="{{obj.image.url}}">
                                            </a>
                                            <button class="profile-wishlist-list-item-remove"><span
                                                    class="mdi mdi-close"></span></button>
                                        </div>
                                        <div class="profile-wishlist-list-item-content">
                                            <div class="profile-wishlist-list-item-content-container">
                                                <a href="{% url 'product:detail' obj.category obj.id %}">
                                                    <h4>{{obj.name}}</h4>
                                                </a>
                                               
                                            </div>
                                            <div class="profile-wishlist-list-item-content-container">
                                                <div class="profile-wishlist-list-item-price">
                                                    <span>{{obj.price}}</span>
                                                    <span>تومان</span>

                                                    <a href="{% url 'product:detail' obj.category obj.id %}" class="profile-wishlist-list-item-button">مشاهده
                                                        محصول</a>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    {% endfor %}
                                    {% else %}
                                    <div class="alert alert-warning" role="alert">
                                       {{msg}}
                                      </div>
                                    {% endif %}

                                </ul>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock main %}